const urlBase = '/src/modules/DrawDiagram/utils/assets/img/newDiagram'
const urlBaseView = '/src/modules/DrawDiagram/utils/assets/img/diagramAction'
export const ListImg = () => [
	{
		id: 1,
		name: 'Cisterna enterrada',
		src: `${urlBase}/Cisterna.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		animation: 'wave',
		configAnimation: {
			color: '#00eeff',
			margenLeft: 0.023,
			margenTop: 0.16, //0.16
			margenTopMin: 0.16,
			margenTopMax: 0.9,
			margenBotonLeft: 0.8,
			widthTop: 96,
			widthBottom: 92,
			heightLeft: 74,
			heightRight: 74,
		},
		variables: {
			nivel: { id_variable: 0, show: false, require: true },
			egreso: { id_variable: 0, show: false, require: false },
		},
	},
	{
		id: 2,
		name: 'Cisterna horizontal',
		src: `${urlBase}/tanque_horizontal.png`,
		srcView: `${urlBaseView}/tanque_horizontal.png`,
		animation: 'wave',
		configAnimation: {
			color: '#00eeff',
			margenLeft: 0.1,
			margenTop: 0.22,
			margenTopMin: 0.22,
			margenTopMax: 0.76,
			margenBotonLeft: 0,
			widthTop: 76,
			widthBottom: 75,
			heightLeft: 53,
			heightRight: 53,
		},
		variables: { nivel: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 3,
		name: 'Cisterna Vertical Simple',
		src: `${urlBase}/Tanques_agua_simple.png`,
		srcView: `${urlBaseView}/Tanques_agua_simple.png`,
		animation: 'wave',
		configAnimation: {
			color: '#00eeff',
			margenLeft: 0.3,
			margenTop: 0.15,
			margenTopMin: 0.15,
			margenTopMax: 0.81,
			margenBotonLeft: 0,
			widthTop: 43,
			widthBottom: 43,
			heightLeft: 66,
			heightRight: 66,
		},
		variables: { nivel: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 4,
		name: 'Cisterna Vertical Multiple',
		src: `${urlBase}/Tanques_agua_multiple.png`,
		srcView: `${urlBaseView}/Tanques_agua_multiple.png`,
		animation: 'wave',
		configAnimation: {
			color: '#00eeff',
			margenLeft: 0.48,
			margenTop: 0.15,
			margenTopMin: 0.15,
			margenTopMax: 0.82,
			margenBotonLeft: 0,
			widthTop: 23,
			widthBottom: 23,
			heightLeft: 68,
			heightRight: 68,
		},
		variables: { nivel: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 5,
		name: 'Tanque elevado',
		src: `${urlBase}/tanque_elevado2.png`,
		srcView: `${urlBase}/tanque_elevado2.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 6,
		name: 'Caudalímetro',
		src: `${urlBase}/Caudalimetro.png`,
		srcView: `${urlBase}/cisternaTerminada.png`,
		variables: { caudal: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 7,
		name: 'Dosificador',
		src: `${urlBase}/Dosificador_quimicos.png`,
		srcView: `${urlBase}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 8,
		name: 'Barómetro',
		src: `${urlBase}/Barometro.png`,
		srcView: `${urlBase}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 9,
		name: 'Presostato',
		src: `${urlBase}/Presostato_rojo.png`,
		srcView: `${urlBaseView}/Presostato_rojo.png`,
		animation: 'boolean',
		optionsImage: {
			error: `${urlBaseView}/Presostato_rojo.png`,
			success: `${urlBaseView}/Presostato_verde.png`,
		},
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 10,
		name: 'Bidón',
		src: `${urlBase}/Estanque_cloro.png`,
		srcView: `${urlBaseView}/Estanque_cloro3.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
		animation: 'wave',
		configAnimation: {
			color: '#ffea00',
			margenLeft: 0.2,
			margenBotonLeft: 0,
			margenTop: 0.22,
			margenTopMin: 0.21,
			margenTopMax: 0.78,
			widthTop: 65,
			widthBottom: 64,
			heightLeft: 56,
			heightRight: 56,
		},
	},
	{
		id: 11,
		name: 'Llave de paso',
		src: `${urlBase}/Valvula.png`,
		srcView: `${urlBase}/Valvula_OFF.png`,
		animation: 'boolean',
		optionsImage: {
			error: '/src/modules/DrawDiagram/utils/assets/img/diagramAction/Valvula__BAD.png',
			success: '/src/modules/DrawDiagram/utils/assets/img/diagramAction/Valvula__OK.png',
			default: '/src/modules/DrawDiagram/utils/assets/img/diagramAction/Valvula_OFF.png',
		},
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 12,
		name: 'Bomba presurizadora',
		src: `${urlBase}/Bomba_presurizadora.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 13,
		name: 'Bomba sumergible',
		src: `${urlBase}/Bomba_sumergible.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 14,
		name: 'Ósmosis',
		src: `${urlBase}/ósmosis.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 15,
		name: 'Filtro multimedia',
		src: `${urlBase}/Filtro_Multimedia.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 16,
		name: 'Filtro cartucho',
		src: `${urlBase}/Filtro_cartucho.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 17,
		name: 'Filtro de manga',
		src: `${urlBase}/Tubos_osmosis.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 18,
		name: 'Instrumento',
		src: `${urlBase}/Sonda_conductimetro.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
	{
		id: 19,
		name: 'Indicador Luminoso',
		src: `${urlBase}/Sonda_conductimetro.png`,
		srcView: `${urlBaseView}/cisternaTerminada.png`,
		variables: { variable1: { id_variable: 0, show: false, require: false } },
	},
]
