const urlBase = '/src/modules/DrawDiagram/utils/assets/img/newDiagram'
export const ListImg = () => [
	{
		id: 1,
		name: 'Cisterna enterrada',
		src: `${urlBase}/Cisterna.png`,
		variables: { nivel: { id_variable: 0, show: false } },
	},
	{
		id: 2,
		name: 'Cisterna horizontal',
		src: `${urlBase}/tanque_horizontal.png`,
		variables: { nivel: { id_variable: 0, show: false } },
	},
	{
		id: 3,
		name: 'Cisterna Vertical Simple',
		src: `${urlBase}/Tanques_agua_simple.png`,
		variables: { nivel: { id_variable: 0, show: false } },
	},
	{
		id: 4,
		name: 'Cisterna Vertical Multiple',
		src: `${urlBase}/Tanques_agua_multiple.png`,
		variables: { nivel: { id_variable: 0, show: false } },
	},
	{
		id: 5,
		name: 'Tanque elevado',
		src: `${urlBase}/tanque_elevado2.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 6,
		name: 'Caudalímetro',
		src: `${urlBase}/Caudalimetro.png`,
		variables: { caudal: { id_variable: 0, show: false } },
	},
	{
		id: 7,
		name: 'Dosificador',
		src: `${urlBase}/Dosificador_quimicos.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 8,
		name: 'Barómetro',
		src: `${urlBase}/Barometro.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 9,
		name: 'Presostato',
		src: `${urlBase}/Presostato_rojo.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 10,
		name: 'Bidón',
		src: `${urlBase}/Estanque_cloro.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 11,
		name: 'Llave de paso',
		src: `${urlBase}/Valvula.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 12,
		name: 'Bomba presurizadora',
		src: `${urlBase}/Bomba_presurizadora.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 13,
		name: 'Bomba sumergible',
		src: `${urlBase}/Bomba_sumergible.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 14,
		name: 'Ósmosis',
		src: `${urlBase}/ósmosis.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 15,
		name: 'Filtro multimedia',
		src: `${urlBase}/Filtro_Multimedia.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 16,
		name: 'Filtro cartucho',
		src: `${urlBase}/Filtro_cartucho.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 17,
		name: 'Filtro de manga',
		src: `${urlBase}/Tubos_osmosis.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 18,
		name: 'Instrumento',
		src: `${urlBase}/Sonda_conductimetro.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
	{
		id: 19,
		name: 'Indicador Luminoso',
		src: `${urlBase}/Sonda_conductimetro.png`,
		variables: { variable1: { id_variable: 0, show: false } },
	},
]
